image: node:18

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm ci
          - npm run lint
          - npm run build
          - npm test

  branches:
    develop:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm ci
            - npm run lint
            - npm run build
            - npm test
      - step:
          name: Deploy to Development
          deployment: development
          script:
            - echo "Deploying to development environment"
            # TODO: Add deployment script

    staging:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm ci
            - npm run lint
            - npm run build
            - npm test
      - step:
          name: Deploy to Staging
          deployment: staging
          script:
            - echo "Deploying to staging environment"
            # TODO: Add deployment script 

    main:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm ci
            - npm run lint
            - npm run build
            - npm test
      - step:
          name: Manual Approval for Production
          script:
            - echo "Waiting for manual approval..."
          trigger: manual
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - echo "Deploying to production environment"
            # TODO: Add deployment script