image: node:18

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm test
    - step: &lint
        name: Code linting
        script:
          - npm install eslint
          - npx eslint .
        caches:
          - node
    - step: &deploy
        name: Deploy to DigitalOcean
        deployment: production
        script:
          - apt-get update && apt-get install -y sshpass
          - sshpass -p $DO_SSH_PASSWORD ssh -o StrictHostKeyChecking=no nodejs@$DO_SERVER_IP "
              cd /var/www/html &&
              git pull origin main &&
              npm install &&
              npm run build &&
              pm2 restart sharemy-backend
            "

pipelines:
  default:
    - parallel:
        - step: *build-test
        - step: *lint
  branches:
    main:
      - parallel:
          - step: *build-test
          - step: *lint
      - step: *deploy