image: node:18

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm test
    - step: &lint
        name: Code linting
        script:
          - npm install eslint
          - npx eslint .
        caches:
          - node
    - step: &deploy
        name: Deploy to DigitalOcean
        deployment: production
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: dev@sharemyinc.com
              SERVER: 134.122.19.233
              COMMAND: |
                cd /home/dev@sharemyinc.com/sharemy-backend
                git pull origin main
                npm install
                # pm2 restart sharemy-backend
                npm run start:prod

pipelines:
  default:
    - parallel:
        - step: *build-test
        - step: *lint
  branches:
    main:
      - parallel:
          - step: *build-test
          - step: *lint
      - step: *deploy